### ISSUE TITLE
Ability to launch multiple Factorio servers from same interface

### ISSUE THREAD

**Issue by mroote** [mroote/factorio-server-manager#3]
Currently a FactorioServer struct is initialized when the server is first started in order to track status of the Factorio game server.

To have the ability to launch multiple Factorio servers this struct should be initialized later when launching the server.  

Users should be able to select settings for the server and save for later use.  

When launching the server a menu can be added to allow selecting which configuration of server to launch.

**Comment by TheGrandPackard** [comment]
Hi @MajorMJR! I am interested in this functionality as well for the users I help manage a server for. I am going to work on this with @SilverSix311 as a learning tool for him. 

Before we start, has there been any significant work towards this functionality? I came to the same conclusion about instances and also the overhauling of the API and then the frontend to accommodate the new functionality. It'll be quite the pull request but it'll be worth it. Otherwise I'll just keep it forked for those that want access to it.

**Comment by MajorMJR** [comment]
Hey @TheGrandPackard I haven't started coding anything for this feature, just had a thought that it would be useful and added an issue so I wouldn't forget.  If you want to start working on this that would be awesome.  

If you have any questions just let me know I would be happy to take in any PR's.
