### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by OnkelDom** [mroote/factorio-server-manager#69]
![image](https://cloud.githubusercontent.com/assets/6128784/24365991/0f0c3294-1318-11e7-9e37-0d495aa063a0.png)

docker-settings:
system: dsm6.1 (custom hw)
![image](https://cloud.githubusercontent.com/assets/6128784/24366102/5eb10234-1318-11e7-8585-5a32eed75a85.png)
![image](https://cloud.githubusercontent.com/assets/6128784/24366141/7dfa8624-1318-11e7-921d-82c2891c1149.png)

Hello,
i have rebuild my factorio server with docker container. The game-server is running as an standalone docker image. the server manager doesnt work with the error in the picture. can anyone help me or say me what is the right way to run it?
thx

**Comment by mroote** [comment]
Hey @OnkelDom, sorry for the delay.

Looks like this was fixed in the PR by @WaeCo https://github.com/mroote/factorio-server-manager/pull/68.  I just tested it now and found another path to fix in the nginx config file, should be all good to go now.

You can grab the latest Docker container from Docker Hub that one is working now.

**Comment by OnkelDom** [comment]
Fixt... thank you
